name: Post to Facebook Page

on:
  workflow_dispatch:
    inputs:
      task:
        description: 'Which task to run'
        required: true
        default: 'daily_words'
        type: choice
        options:
        - daily_words
        - weekly_summary
  schedule:
    # Runs every day at 7:00 AM IST (1:30 AM UTC)
    - cron: '30 1 * * *'
    # Runs every Sunday at 9:00 AM IST (3:30 AM UTC)
    - cron: '30 3 * * 0'

jobs:
  build-and-post:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permission to commit progress

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Determine Task
      id: task_determiner
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "task=${{ github.event.inputs.task }}" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event.schedule }}" == "30 3 * * 0" ]]; then
          echo "task=weekly_summary" >> $GITHUB_OUTPUT
        else
          echo "task=daily_words" >> $GITHUB_OUTPUT
        fi

    - name: Run Python Script
      env:
        GOOGLE_SHEETS_CREDENTIALS_JSON: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS_JSON }}
        PAGE_ID: ${{ secrets.PAGE_ID }}
        PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
        TASK: ${{ steps.task_determiner.outputs.task }}
      run: python main.py

    - name: Commit and push progress
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        if [ -f progress.json ]; then
          git add progress.json
          # Commit only if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "Update word progress tracker"
            git push
          else
            echo "No changes to progress.json to commit."
          fi
        else
          echo "progress.json not found. Nothing to commit."
        fi
